steps:
# build the container imagename:
# docker build -timage namesteps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/boutique-dev-457514/docker-repo/phython-new-app:D1','build-run/.']
# push the container image to the artifact registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/boutique-dev-457514/docker-repo/phython-new-app:D1']
# deploy the container image to cloud run
# gcloud run deploy phython-new-app --image us-central1-docker.pkg.dev/boutique-dev-457514/docker-repo/phython-new-app:A1 --region us-central1 --platform managed --allow-unauthenticated
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'phython-new-app-docker',
         '--image', 'us-central1-docker.pkg.dev/boutique-dev-457514/docker-repo/phython-new-app:D1',
         '--region', 'us-central1',
         '--platform', 'managed',
         '--allow-unauthenticated']
 
  options:
  logging: CLOUD_LOGGING_ONLY
