steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/boutique-dev-457514/docker-repo/phython-new-app:D1', 'build-run/.']
  
# Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/boutique-dev-457514/docker-repo/phython-new-app:D1']
  
# Deploy to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'phython-new-app-docker',
         '--image', 'us-central1-docker.pkg.dev/boutique-dev-457514/docker-repo/phython-new-app:D1',
         '--region', 'us-central1',
         '--platform', 'managed',
         '--allow-unauthenticated']

options:
  logging: CLOUD_LOGGING_ONLY
